name: Create production promotion pull request
on:
  push:
    branches:
      - content
jobs:
  pr-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: content
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
