name: deploy-admin
concurrency: deploy-admin

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'content/**'
      - 'static/uploads/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
            host: intergestalt.dev
            username: root
            key: ${{ secrets.DOKKU_PRIVATE_KEY }}
            script: |
              dokku maintenance:enable bestand-admin
              dokku ps:rebuild bestand-admin
              dokku maintenance:disable bestand-admin
