name: deploy
concurrency: deploy

on:
  push:
    branches:
      - master
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '15 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Deploy the application
        uses: thadeu/easily-dokku-action@v1.0.8
        env:
          BRANCH: master # optional
          PROJECT: 2038-news
          FLAGS: --force # optional
          PORT: 22 # optional
          SSH_PRIVATE_KEY: ${{ secrets.DOKKU_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.DOKKU_PUBLIC_KEY }}
          SSH_HOST: ${{ secrets.DOKKU_HOST }}
